#!/usr/bin/env bash

if [ ! -z $1 ]; then
   if [ "$1" = "dm" ]; then
      madonctl toot --visibility=direct --stdin
   else
      madonctl toot --in-reply-to=$1 --add-mentions --same-visibility --stdin
   fi
else
   madonctl toot --stdin
fi
