#!/usr/bin/env bash

# it's a dm!
if [ "$1" = "dm" ]; then
   if [ "$2" = "file" ]; then
      if [[ $3 =~ ^http ]]; then
         madonctl toot --visibility=direct --file <(wget -q -O - $3) --stdin
      else
         madonctl toot --visibility=direct --file "${3}" --stdin
      fi
   else
      madonctl toot --visibility=direct --stdin
   fi
   exit 0
# it's a reply!
elif [[ $1 =~ ^[0-9]+$ || $1 == http* ]]; then
   case $1 in
      [0-9]*)
         status=$1
         ;;
      http*)
         status="$(madonctl search "$1" --template '{{with index .statuses 0}}{{.id}}{{end}}')"
         ;;
   esac
   if [ "$2" = "file" ]; then
      if [[ $3 =~ ^http ]]; then
         madonctl toot --in-reply-to=$status --add-mentions --same-visibility --file <(wget -q -O - $3) --stdin
      else
         madonctl toot --in-reply-to=$status --add-mentions --same-visibility --file "${3}" --stdin
      fi
   else
      madonctl toot --in-reply-to=$status --add-mentions --same-visibility --stdin
   fi
   exit 0
# it must be a toot if nothing else
else
   if [ "$1" = "file" ]; then
      if [[ $2 =~ ^http ]]; then
         madonctl toot --file <(wget -q -O - $2) --stdin
      else
         madonctl toot --file "${2}" --stdin
      fi
   else
      madonctl toot --stdin
   fi
   exit 0
fi
