#!/usr/bin/env bash

if [[ -z $1 ]]; then
   echo "Usage: $(basename $0) status-id"
   exit 1
fi

regex='^[0-9]+$'

if [[ $1 =~ $regex ]]; then
   status=$1
else
   status="$(madonctl search "$1" --template '{{with index .statuses 0}}{{printf "%.0f" .id}}{{end}}')"
fi

madonctl status --status-id $status delete
